### ISSUE TITLE
cached true in last-alarm

### ISSUE THREAD

**Issue by Frone87** [Dustin1358/Raspberry-Pi-Divera-Monitor#1]
Hi,

ich hab zeitgleich auch den Divera Support kontaktiert.
Unter:
https://www.divera247.com/api/last-alarm?accesskey=
wurde für Divera-Interne Fehlerbehebung {"success":false,"**cached":true**} hinzugefügt.
Somit geht der Bildschirm auch an, wenn kein Alarm anliegt (da success ja immer vorhanden ist) und cached auf true geht.

--> Außerdem sind die Scripts divera_script.py und divera_script_motion.py im Wiki vertauscht und somit an der falschen Stelle eingebunden/abgelegt.

Ich habs wie folgt gelöst (Abfrage Probealarm hab ich gelöscht, gibts bei uns nicht).
```

try:
	with urllib.request.urlopen(API_URL) as url:
		data = json.loads(url.read().decode())
		ALARM_ACTIVE = data["success"]
```

Oben natürlich "import json" hinzufügen.

Bin weit davon entfernt wirklich mit python programmieren zu können, aber die Lösung war vermutlich recht einfach.

**Comment by Dustin1358** [comment]
Hi,
den Fehler hatte ich auch festgestellt und gefixed aber anscheinend vergessen die Veränderung zu push.

Ich hatte versucht eine JSON-Library zu umgehen, die schien mir für diese eine Zeile etwas zu viel, deswegen habe ich das Problem ungefähr so gelöst:

` alarm_active = "\"success\":false" in requests.get(API_URL).content.decode()`

Morgen Nachmittag werde ich die Zeile entsprechend anpassen und heute Abend mir die vertauschten Skripte angucken.

- [ ] divera_script.py und divera_script_motion.py im Wiki vertauscht

- [ ] Alarm immer aktive fixen

Danke für das melden der Fehler!

**Comment by Dustin1358** [comment]
An welcher Stelle ist das diver_script.py und divera_script_motion.py vertauscht?
Ich hab so jetzt erstmal kein Fehler gefunden.

**Comment by CrazyFire66** [comment]
Das ist im Wiki von Divera vertauscht.

https://help.divera247.com/pages/viewpage.action?pageId=44171296

**Comment by Dustin1358** [comment]
Der Bug ist im Code nun gefixed, wegen dem Wiki schreibe ich divera an.

**Comment by Frone87** [comment]
vielen Dank für das Script.
Kleiner Hinweis noch: Die Skrips sind nun im Divera-Wiki an der richtigen Stelle.
Aber: Bugfix von diesem issue ist dort noch nicht gefixt.

**Comment by Dustin1358** [comment]
Danke für den Hinweis, dort ist jetzt auch die aktuelle Version des Scripts hinterlegt.
