### ISSUE TITLE
Problem beim Laden des Monitors

### ISSUE THREAD

**Issue by The-Trade** [Dustin1358/Raspberry-Pi-Divera-Monitor#3]
Hallo

Danke erstmal für den Code.

ich habe den Monitor nach deiner Anleitung eingerichtet.
wenn ich den Befehl monitor on benutze öffnet sich wie gewollt chromium.

Allerding kommt bei mir die Fehlermeldung 

Die Webseite ist nicht erreichbar
Die Server-IP-Adresse von %7Bhttps wurde nicht gefunden.
DNS_PROBE_FINISHED_NXDOMAIN

hier nochmal ein Bild von der sh
![Divera](https://user-images.githubusercontent.com/75371761/100874213-86749400-34a4-11eb-8ef2-b0120230918d.PNG)

über ein Antwort und Lösung des Problems würde ich mich sehr freuen.

**Comment by Dustin1358** [comment]
Das klingt als gäbe es generell ein Problem mit der Internetverbindung. Kann der Monitor den aufgerufen werden wenn  man ihn manuell über Chromium aufruft?

**Comment by The-Trade** [comment]
Also Webseiten haben sich über den Chromium aufrufen lassen, den Monitor direkt habe ich nicht Probiert.
Ich habe das Problem aber Mittlerweile anderweitig gelöst. Trotzdem danke für deine Hilfe.

**Comment by Patty0409** [comment]
Hallo,

auch ich danke für den Code. 
Leider habe ich genau das gleiche Problem und finde keine andere Lösung.

Der Autologin funktioniert über Chromium aufjedenfall.

**Comment by Dustin1358** [comment]
Fehler wurde hier identifiziert und behoben: https://github.com/Dustin1358/Raspberry-Pi-Divera-Monitor/issues/5
