### ISSUE TITLE
Tipp bezüglich der richtigen Accesskeys

### ISSUE THREAD

**Issue by Brun0000** [Dustin1358/Raspberry-Pi-Divera-Monitor#4]
Hallo,
ich bin eigentlich Computertechnisch nicht ganz auf den Kopf gefallen, hatte/habe aber trotzdem ein paar Probleme bei der Einrichtung, da ich nicht wusste welchen Accesskey ich schlussendlich eintragen musste. Könntest du dort bitte noch einen Kommentar im Code hinterlassen? z.B. #autologin(monitor-account), #accesskey(alarm)

Lieben Gruß

**Comment by Dustin1358** [comment]
Hallo,
das klingt nach einer guten Idee! Ich selbst habe in unsere Einheit keine Adminrechte nei Divera und die entsprechenden Keys einfach bekommen.
Kannst du mir sagen wo am besten welcher Kommentar hinzugefügt werden soll dann werde ich das ergänzen.

Liebe Grüße

**Comment by Brun0000** [comment]
Moin,
sorry für die späte Antwort. Ich habe die Keys leider auch nur vom Wehrführer erhalten. Seitdem haben wir uns wegen Corona nicht gesehen/getroffen. Ich hoffe, dass ich im laufe des Jahres noch an die richtigen Bezeichnungen komme.

Liebe Grüße

**Comment by Ranulf83** [comment]
Unter Verwaltung -> Setup -> Monitore gibt es Monitor-Benutzer, wo das Autologin aktiviert werden muss:
![Screenshot 2021-09-25 144220](https://user-images.githubusercontent.com/40439510/134772092-94da9d2e-4f6d-4ebd-bd4d-9933bcb1343d.jpg)

**Comment by Dustin1358** [comment]
Ich es in die Anleitung und das script gepackt, danke!
