### ISSUE TITLE
Problem beim Laden des Monitor

### ISSUE THREAD

**Issue by Patty0409** [Dustin1358/Raspberry-Pi-Divera-Monitor#5]
Nabend,

zunächst danke für das bereitstellen deines gesamt Codes.
Da steckt einiges an Arbeit drin.

Ich habe den Monitor nach deiner Anleitung eingerichtet und hatte so weiter auch keine großen Probleme.
Wenn der Befehl monitor on geschrieben wird, öffnet sich auch Chromium, wie gewollt.

Allerdings kommt dann wie bei dem Kameraden im Dezember auch die folgende Fehlermeldung:

Die Webseite ist nicht erreichbar.
Die Server-IP-Adresse von %7Bhttps wurde nicht gefunden.
DNS_Probe_FINISHED_NXDOMAIN

Wenn ich den Autologin-Key von Divera direkt in den Chromium eingebe haut alles direkt hin.
Bisher tappe ich auch mit allen versuchen im Dunkeln.

Anbei nochmal ein Bild von der .divera_commands.sh

![2021-02-28-183841_1824x984_scrot](https://user-images.githubusercontent.com/79787728/109427780-3e5a0480-79f4-11eb-921a-e31180220b6a.png)

Über eine Antwort oder vielleicht eine Kontaktaufnahme deinerseits würde ich mich sehr freuen.
Ich vermute das es ja eine Kleinigkeit sein wird, die nachher großes verursacht.

**Comment by Dustin1358** [comment]
Hallo,
ich habe mir das Problem einmal genauer angeguckt und die geschweiften Klammern sind das Problem.
Es muss heißen:
MONITOR=https...
oder:
MONITOR="https..."
aber nicht:
MONITOR={https...}

Alles was im Tutorial manuell ersetzt werden muss hat die Form VARIABLE={ERSETZE_MICH} mit den geschweiften Klammern um es hervorzuheben. Ich sollte aber im Code mit dazu schreiben das die geschweiften Klammern mit ersetzt werden müssen.

**Comment by Patty0409** [comment]
Moin Dustin,

danke für deine schnelle Antwort.
Manchmal sitzt das Problem 50cm vor dem PC.

Jetzt läuft es ohne Probleme und sehr stabil :-)
Besten Dank für deine Hilfe.

**Comment by Dustin1358** [comment]
Perfekt, ich habe im Code auch nochmal einen Kommentar dazugeschrieben.
