### ISSUE TITLE
Probleme mit Bewegungsmelder

### ISSUE THREAD

**Issue by Chicken1304** [Dustin1358/Raspberry-Pi-Divera-Monitor#6]
Hallo zusammen,

ich habe das Problem, bei meinem Monitor, dass er sich zwar abschaltet, aber nach ca 45 Sekunden wieder automatisch angeht.
Wenn ich das Skript ausführe steht immer Motion detected. Dies kann aber nicht sein. Der Bewegungsmelder ist in einem Tuch eingehüllt :) 
Hat jemand eine Idee, woran das liegen könnte?

Vielen Dank!

**Comment by Dustin1358** [comment]
Hallo,

ich würde als erstes versuchen die Empfindlichkeit des Sensors runter zu stellen. Manche Sensoren erkennen durchgängig Bewegung wenn sie auf einer hohe Stufe sind. Ansonsten kann dies auch daran liegen das der Sensor an den falschen GPIO Pins angeschlossen ist. Ich hatte den Sensor zum testen immer in einen Karton gepackt und diesen auf den Boden gestellt damit dort auch nicht durch Vibrationen durch das tippen oder sonstiges ausversehen eine Bewegung erkannt wird. Ich hoffe das dir etwas davon vielleicht hilft!

**Comment by Chicken1304** [comment]
Hallo Dustin,
leider ist die schon runter gestellt und in einem Tuch eingewickelt. Wackeln kann auch nichts. An sich funktioniert er auch. Wenn der Bildschirm kurz aus ist und man sich davor bewegt, geht der Monitor auch an. Leider halt auch nach ca 45 Sekunden auch ohne Bewegung. Und das immer so ca 45 Sekunden nach ausgehen.

**Comment by Dustin1358** [comment]
Es ist aus der Ferne sehr schwer festzustellen was das Problem sein könnte. Ich würde im Script die Befehle die den Bildschirm ein/ausschalten auskommentieren und das Script manuell über die Kommandozeile starten um zu gucken ob der Sensor wirklich die Bewegungen passend erkennt oder ob man dort ein Muster erkennen kann. Ich könnte mir vorstellen das der Sensor falsch angeschlossen ist dann sollte er aber auch keine Bewegung erkennen können. Was man noch überprüfen sollte ist, dass das Jumper Set auf High steht. Dies sollte vermutlich nicht das Problem sein aber muss auch passend eingestellt sein: https://elektro.turanis.de/html/prj108/hc-sr501_details.jpg

**Comment by Chicken1304** [comment]
War alles richtig angeschlossen und so. Habe es jetzt anders gemacht und die Monitorsteckdose hat jetzt einen Bewegungsmelder und steuert den.
