### ISSUE TITLE
Monitor geht bei Alarm nicht an

### ISSUE THREAD

**Issue by Jochen85** [Dustin1358/Raspberry-Pi-Divera-Monitor#9]
Hi,

hab alles nach Anleitung eingestellt aber der Monitor (ein Fernseher) geht bei Alarm nicht an.
Wenn ich den Monitor mit dem Befehl "screen on" dann starte dann zeigt er alles an wie er soll. 
Ausgeschaltet wird der Monitor beim beenden des Alarm auch nicht. Aber auch hier geht der Befehl "screen off" und der Monitor wird abgeschaltet.

Wenn ich den Pi starte und es ist kein Dienstabend dann wird er nach kurzer Zeit abgeschaltet, bei Dienstabend bleibt er an.
Da habe ich aber noch nicht im Detail getestet da mir der Alarm wichtiger ist das der funktioniert.

Hab keine Idee woran das liegen kann.

**Comment by Jochen85** [comment]
Inzwischen habe ich entdeckt das der Befehl "monitor on" auch nicht funktioniert bei eingabe im Terminal "Monitor off" funktioniert aber.
Mir kommt es so vor als würder das .divera_script.py nur ein mal durchlaufen.

**Comment by Jochen85** [comment]
Hab den Fehler gefunden. 
Ich habe in der .divera_script.py bei Accesskey den Autologinkey vom DIVERA Monitor-Benutzer eingegeben. Das ist der falsche. Bei DIVERA in der Verwaltung unter Schnittstellen -> API -> Autorisierung habe ich den richtigen Accesskey dann gefunden. Bin immer davon ausgegangen das die ganzen Zugangsdaten sich auf den Monitor-Benutzer beziehen.

**Comment by Dustin1358** [comment]
Hab das in der Anleitung nochmal genauer spezifiziert mit deiner Info wo man den Key finden kann, danke!
